version: "3.9"

volumes:
  postgres-data:
  redis-data:
  minio-data:
  minio-storage:

networks:
  net:

services:
  postgres:
    container_name: postgres-events-prod
    image: postgres:15
    restart: always
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    networks:
      - net
  
  redis:
    container_name: redis-events-prod
    image: redis/redis-stack-server:6.2.6-v15
    env_file:
      - .env
    volumes:
      - redis-data:/data
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - net

  minio:
    container_name: minio-events-prod
    image: minio/minio:RELEASE.2024-01-18T22-51-28Z
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/var/lib/minio
      - minio-storage:/data
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file: .env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://minio:9000/minio/health/live" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks:
      - net


  events-backend:
    build:
      context: .
      dockerfile: Dockerfile

    restart: always

    env_file: .env

    ports:
      - "8000:8000"

    networks:
      - net

    depends_on:
      - postgres
      - redis
      - minio
