version: "3.9"

volumes:
  postgres-data:

networks:
  net:

services:
  postgres:
    container_name: postgres-events
    image: postgres:15
    restart: always
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=512MB"
      - "-c"
      - "work_mem=12MB"
      - "-c"
      - "maintenance_work_mem=128MB"
    networks:
      - net
