"""Add event and event content

Revision ID: 00f70d2a6d14
Revises: e09a1992a551
Create Date: 2024-02-04 15:10:34.621169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "00f70d2a6d14"
down_revision = "e09a1992a551"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA events")
    op.create_table(
        "event",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("datetime_start", sa.DateTime(), nullable=False),
        sa.Column("datetime_end", sa.DateTime(), nullable=False),
        sa.Column("sid", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("sid"),
        schema="events",
    )
    op.create_index(
        op.f("ix_events_event_sid"), "event", ["sid"], unique=True, schema="events"
    )
    op.create_table(
        "event_content",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("event_sid", sa.UUID(), nullable=False),
        sa.Column("sid", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_sid"],
            ["events.event.sid"],
        ),
        sa.PrimaryKeyConstraint("sid"),
        schema="events",
    )
    op.create_index(
        op.f("ix_events_event_content_sid"),
        "event_content",
        ["sid"],
        unique=True,
        schema="events",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_events_event_content_sid"), table_name="event_content", schema="events"
    )
    op.drop_table("event_content", schema="events")
    op.drop_index(op.f("ix_events_event_sid"), table_name="event", schema="events")
    op.drop_table("event", schema="events")
    op.execute("DROP SCHEMA events")
    # ### end Alembic commands ###
