"""Added event image table

Revision ID: 07ae6f2e0d2c
Revises: 78b8160d8929
Create Date: 2024-09-29 11:48:19.859147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ae6f2e0d2c'
down_revision = '78b8160d8929'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA event_image")
    op.create_table('event_image',
    sa.Column('sid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('sid'),
    schema='event_image'
    )
    op.drop_constraint('event_event_type_sid_fkey', 'event', type_='foreignkey')
    op.create_foreign_key(None, 'event', 'event_type', ['event_type_sid'], ['sid'], source_schema='events', referent_schema='event_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', schema='events', type_='foreignkey')
    op.create_foreign_key('event_event_type_sid_fkey', 'event', 'event_type', ['event_type_sid'], ['sid'], referent_schema='event_type')
    op.drop_table('event_image', schema='event_image')
    op.execute("DROP SCHEMA event_image")
    # ### end Alembic commands ###
