"""Added image to event table

Revision ID: 0d98255093a4
Revises: 07ae6f2e0d2c
Create Date: 2024-09-29 11:52:56.735142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d98255093a4'
down_revision = '07ae6f2e0d2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_image_sid', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'event', 'event_image', ['event_image_sid'], ['sid'], source_schema='events', referent_schema='event_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', schema='events', type_='foreignkey')
    op.drop_column('event', 'event_image_sid')
    # ### end Alembic commands ###
