"""create_role_x_permission_table

Revision ID: 26a867c42173
Revises: c84f120a28f3
Create Date: 2024-06-12 21:28:38.445501

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "26a867c42173"
down_revision = "c84f120a28f3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role_x_permission",
        sa.Column("sid", sa.Uuid(), nullable=False),
        sa.Column(
            "role_label", sa.SMALLINT(), nullable=False, comment="Role label"
        ),
        sa.Column(
            "permission_label",
            sa.SMALLINT(),
            nullable=False,
            comment="Permission label",
        ),
        sa.Column(
            "access_actions",
            sa.VARCHAR(length=5),
            nullable=False,
            comment="Access actions of role permission",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            comment="Record creating time",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Record updating time",
        ),
        sa.ForeignKeyConstraint(
            ["permission_label"],
            ["security.permission.label"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_label"], ["security.role.label"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("sid"),
        schema="security",
        comment="Table with all role permissions",
    )
    op.create_index(
        op.f("ix_security_role_x_permission_permission_label"),
        "role_x_permission",
        ["permission_label"],
        unique=False,
        schema="security",
    )
    op.create_index(
        op.f("ix_security_role_x_permission_role_label"),
        "role_x_permission",
        ["role_label"],
        unique=False,
        schema="security",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_security_role_x_permission_role_label"),
        table_name="role_x_permission",
        schema="security",
    )
    op.drop_index(
        op.f("ix_security_role_x_permission_permission_label"),
        table_name="role_x_permission",
        schema="security",
    )
    op.drop_table("role_x_permission", schema="security")
    # ### end Alembic commands ###
