"""alter_rename_is_verified_column_to_user_table

Revision ID: 35fc1fe39c7d
Revises: 892995bc4457
Create Date: 2024-06-20 13:15:37.755649

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "35fc1fe39c7d"
down_revision = "892995bc4457"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "is_verified",
        new_column_name="is_verify",
        existing_type=sa.Boolean(),
        server_default="false",
        nullable=False,
        existing_comment="User verified status",
        schema="users",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "is_verify",
        new_column_name="is_verified",
        existing_type=sa.Boolean(),
        server_default="false",
        nullable=False,
        existing_comment="User verified status",
        schema="users",
    )
    # ### end Alembic commands ###
