"""Added event type table

Revision ID: 47e3904bddb6
Revises: 9dc95c86b110
Create Date: 2024-09-27 20:11:41.576574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e3904bddb6'
down_revision = '9dc95c86b110'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA event_type")
    op.create_table('event_type',
    sa.Column('sid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('sid'),
    schema='event_type'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_type', schema='event_type')
    op.execute("DROP SCHEMA event_type")
    # ### end Alembic commands ###
