"""create_event_content_type_table

Revision ID: 4f87b0abcd8b
Revises: 593a6603a18a
Create Date: 2024-06-12 22:51:53.524560

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "4f87b0abcd8b"
down_revision = "593a6603a18a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_content_type",
        sa.Column("label", sa.SMALLINT(), nullable=False),
        sa.Column(
            "name",
            sa.String(),
            nullable=False,
            comment="Event content type name",
        ),
        sa.Column(
            "description",
            sa.String(),
            nullable=False,
            comment="Event content type description",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            comment="Record creating time",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Record updating time",
        ),
        sa.PrimaryKeyConstraint("label"),
        schema="events",
        comment="Table with all event content types",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event_content_type", schema="events")
    # ### end Alembic commands ###
