"""create_event_pull_table

Revision ID: 51987fae3b6d
Revises: fc8ecdce47d8
Create Date: 2024-06-13 00:25:42.498506

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "51987fae3b6d"
down_revision = "fc8ecdce47d8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_pull",
        sa.Column("sid", sa.Uuid(), nullable=False),
        sa.Column("user_sid", sa.Uuid(), nullable=False, comment="User SID"),
        sa.Column("event_sid", sa.Uuid(), nullable=False, comment="Event SID"),
        sa.Column(
            "event_content_sid",
            sa.Uuid(),
            nullable=False,
            comment="Event content SID",
        ),
        sa.Column(
            "event_role_label",
            sa.SMALLINT(),
            nullable=False,
            comment="Event role label",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            comment="Record creating time",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Record updating time",
        ),
        sa.ForeignKeyConstraint(
            ["event_content_sid"],
            ["events.event_content.sid"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["event_role_label"], ["security.role.label"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["event_sid"], ["events.event.sid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_sid"], ["users.user.sid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("sid"),
        schema="events",
        comment="Table with all event pulls",
    )
    op.create_index(
        op.f("ix_events_event_pull_event_content_sid"),
        "event_pull",
        ["event_content_sid"],
        unique=False,
        schema="events",
    )
    op.create_index(
        op.f("ix_events_event_pull_event_role_label"),
        "event_pull",
        ["event_role_label"],
        unique=False,
        schema="events",
    )
    op.create_index(
        op.f("ix_events_event_pull_event_sid"),
        "event_pull",
        ["event_sid"],
        unique=False,
        schema="events",
    )
    op.create_index(
        op.f("ix_events_event_pull_user_sid"),
        "event_pull",
        ["user_sid"],
        unique=False,
        schema="events",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_events_event_pull_user_sid"),
        table_name="event_pull",
        schema="events",
    )
    op.drop_index(
        op.f("ix_events_event_pull_event_sid"),
        table_name="event_pull",
        schema="events",
    )
    op.drop_index(
        op.f("ix_events_event_pull_event_role_label"),
        table_name="event_pull",
        schema="events",
    )
    op.drop_index(
        op.f("ix_events_event_pull_event_content_sid"),
        table_name="event_pull",
        schema="events",
    )
    op.drop_table("event_pull", schema="events")
    # ### end Alembic commands ###
