"""alter_nullabel_description_column_to_event_table

Revision ID: 74a4163caa1c
Revises: 67ca1b2f8130
Create Date: 2024-06-17 21:25:42.627340

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "74a4163caa1c"
down_revision = "67ca1b2f8130"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "event",
        "description",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_comment="Event description",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "event",
        "description",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_comment="Event description",
    )
    # ### end Alembic commands ###
