"""alter_nullabel_event_content_sid_column_to_event_file_table

Revision ID: 77d3997d3937
Revises: 6815a7a6f8b3
Create Date: 2024-06-17 12:29:23.399816

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "77d3997d3937"
down_revision = "6815a7a6f8b3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "event_file",
        "event_content_sid",
        existing_type=sa.UUID(),
        nullable=True,
        existing_comment="Event content SID",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "event_file",
        "event_content_sid",
        existing_type=sa.UUID(),
        nullable=False,
        existing_comment="Event content SID",
    )
    # ### end Alembic commands ###
