"""Added event attributes

Revision ID: 78b8160d8929
Revises: b63d106dbe1f
Create Date: 2024-09-28 00:42:27.001010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b8160d8929'
down_revision = 'b63d106dbe1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('event', sa.Column('description', sa.String(), nullable=False))
    op.add_column('event', sa.Column('event_type_sid', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'event', 'event_type', ['event_type_sid'], ['sid'], source_schema='events', referent_schema='event_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', schema='events', type_='foreignkey')
    op.drop_column('event', 'event_type_sid')
    op.drop_column('event', 'description')
    # ### end Alembic commands ###
