"""create_event_like_table

Revision ID: 7d616c23dc7c
Revises: f79a36eb539a
Create Date: 2024-06-13 00:27:56.059087

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "7d616c23dc7c"
down_revision = "f79a36eb539a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_like",
        sa.Column("sid", sa.Uuid(), nullable=False),
        sa.Column("user_sid", sa.Uuid(), nullable=False, comment="User SID"),
        sa.Column("event_sid", sa.Uuid(), nullable=False, comment="Event SID"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            comment="Record creating time",
        ),
        sa.ForeignKeyConstraint(
            ["event_sid"], ["events.event.sid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_sid"], ["users.user.sid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("sid"),
        schema="metrics",
        comment="Table with all event likes",
    )
    op.create_index(
        op.f("ix_metrics_event_like_event_sid"),
        "event_like",
        ["event_sid"],
        unique=False,
        schema="metrics",
    )
    op.create_index(
        op.f("ix_metrics_event_like_user_sid"),
        "event_like",
        ["user_sid"],
        unique=False,
        schema="metrics",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_metrics_event_like_user_sid"),
        table_name="event_like",
        schema="metrics",
    )
    op.drop_index(
        op.f("ix_metrics_event_like_event_sid"),
        table_name="event_like",
        schema="metrics",
    )
    op.drop_table("event_like", schema="metrics")
    # ### end Alembic commands ###
