"""alter_user_hashed_password_column_to_nullable

Revision ID: 7e7764d8b9db
Revises: acb7cb33ae26
Create Date: 2024-06-15 20:07:49.681724

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "7e7764d8b9db"
down_revision = "acb7cb33ae26"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "hashed_password",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_comment="User hashed password",
        schema="users",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "hashed_password",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_comment="User hashed password",
        schema="users",
    )
    # ### end Alembic commands ###
