"""alter_nullabel_event_conten_sid_column_to_event_address_table

Revision ID: 892995bc4457
Revises: 02d5cdac3ed6
Create Date: 2024-06-17 21:30:33.891932

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "892995bc4457"
down_revision = "02d5cdac3ed6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "event_address",
        "event_content_sid",
        existing_type=sa.UUID(),
        nullable=True,
        existing_comment="Event content SID",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "event_address",
        "event_content_sid",
        existing_type=sa.UUID(),
        nullable=False,
        existing_comment="Event content SID",
    )
    # ### end Alembic commands ###
