"""create_event_view_table

Revision ID: acb7cb33ae26
Revises: 7d616c23dc7c
Create Date: 2024-06-13 00:28:31.171557

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "acb7cb33ae26"
down_revision = "7d616c23dc7c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_view",
        sa.Column("sid", sa.Uuid(), nullable=False),
        sa.Column("user_sid", sa.Uuid(), nullable=False, comment="User SID"),
        sa.Column("event_sid", sa.Uuid(), nullable=False, comment="Event SID"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            comment="Record creating time",
        ),
        sa.ForeignKeyConstraint(
            ["event_sid"], ["events.event.sid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_sid"], ["users.user.sid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("sid"),
        schema="metrics",
        comment="Table with all event views",
    )
    op.create_index(
        op.f("ix_metrics_event_view_event_sid"),
        "event_view",
        ["event_sid"],
        unique=False,
        schema="metrics",
    )
    op.create_index(
        op.f("ix_metrics_event_view_user_sid"),
        "event_view",
        ["user_sid"],
        unique=False,
        schema="metrics",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_metrics_event_view_user_sid"),
        table_name="event_view",
        schema="metrics",
    )
    op.drop_index(
        op.f("ix_metrics_event_view_event_sid"),
        table_name="event_view",
        schema="metrics",
    )
    op.drop_table("event_view", schema="metrics")
    # ### end Alembic commands ###
