"""Added event content type table

Revision ID: bd07e2429ee8
Revises: 7be14e702f97
Create Date: 2024-09-29 12:44:24.890664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd07e2429ee8'
down_revision = '7be14e702f97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA event_content_type")
    op.create_table('event_content_type',
    sa.Column('sid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('sid'),
    schema='event_content_type'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_content_type', schema='event_content_type')
    op.execute("DROP SCHEMA event_content_type")
    # ### end Alembic commands ###
