"""Added event content type table

Revision ID: c5793bec67c2
Revises: 47e3904bddb6
Create Date: 2024-09-27 20:12:52.911081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5793bec67c2'
down_revision = '47e3904bddb6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA event_content_type")
    op.create_table('event_content_type',
    sa.Column('sid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('sid'),
    schema='event_content_type'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_content_type', schema='event_content_type')
    op.execute("DROP SCHEMA event_content_type")
    # ### end Alembic commands ###
