"""create_role_table

Revision ID: c84f120a28f3
Revises: 7b764772a878
Create Date: 2024-06-12 21:04:26.672565

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "c84f120a28f3"
down_revision = "7b764772a878"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column("label", sa.SMALLINT(), nullable=False),
        sa.Column("name", sa.String(), nullable=False, comment="Role name"),
        sa.Column(
            "description",
            sa.String(),
            nullable=False,
            comment="Role description",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            comment="Record creating time",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Record updating time",
        ),
        sa.PrimaryKeyConstraint("label"),
        schema="security",
        comment="Table with all roles",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("role", schema="security")
    # ### end Alembic commands ###
