"""create_event_file_type_table

Revision ID: c8fb4ebf0fcf
Revises: 4f87b0abcd8b
Create Date: 2024-06-12 22:53:45.174333

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "c8fb4ebf0fcf"
down_revision = "4f87b0abcd8b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_file_type",
        sa.Column("label", sa.SMALLINT(), nullable=False),
        sa.Column(
            "name", sa.String(), nullable=False, comment="Event file type name"
        ),
        sa.Column(
            "description",
            sa.String(),
            nullable=False,
            comment="Event file type description",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            comment="Record creating time",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Record updating time",
        ),
        sa.PrimaryKeyConstraint("label"),
        schema="events",
        comment="Table with all event file types",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event_file_type", schema="events")
    # ### end Alembic commands ###
