"""create_event_content_table

Revision ID: d7c64c941447
Revises: 933a7e137029
Create Date: 2024-06-12 22:56:37.158240

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "d7c64c941447"
down_revision = "933a7e137029"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_content",
        sa.Column("sid", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False, comment="Event name"),
        sa.Column(
            "description",
            sa.String(),
            nullable=False,
            comment="Event description",
        ),
        sa.Column(
            "type_label",
            sa.SMALLINT(),
            nullable=False,
            comment="Event content type label",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            comment="Record creating time",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Record updating time",
        ),
        sa.ForeignKeyConstraint(
            ["type_label"],
            ["events.event_content_type.label"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("sid"),
        schema="events",
        comment="Table with all events content",
    )
    op.create_index(
        op.f("ix_events_event_content_type_label"),
        "event_content",
        ["type_label"],
        unique=False,
        schema="events",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_events_event_content_type_label"),
        table_name="event_content",
        schema="events",
    )
    op.drop_table("event_content", schema="events")
    # ### end Alembic commands ###
