"""Added event content table

Revision ID: f31080f5be45
Revises: bd07e2429ee8
Create Date: 2024-09-29 12:45:37.662303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31080f5be45'
down_revision = 'bd07e2429ee8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA event_content")
    op.create_table('event_content',
    sa.Column('sid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('event_content_type_sid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['event_content_type_sid'], ['event_content_type.event_content_type.sid'], ),
    sa.PrimaryKeyConstraint('sid'),
    schema='event_content'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_content', schema='event_content')
    op.execute("DROP SCHEMA event_content")
    # ### end Alembic commands ###
