name: CI

on:
  push:
    branches: [ "master"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/events-backend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            cd ${{ secrets.PROJECT_FOLDER }};
            git checkout master;
            git pull;
            echo "${{ secrets.PROD_ENV }}" > .env
            docker-compose --file docker-compose.prod.yaml down;
            docker container rm events-backend-events-backend-1 --force
            docker image rm strannik1105/events-backend strannik1105/events-backend --force
            docker-compose --file docker-compose.prod.yaml up -d;
            docker system prune --all --force;
